### ISSUE TITLE
Allow redirection of paths

### ISSUE THREAD

**Issue by exploide** [nephila/djangocms-redirect#2]
Currently one can only redirect a fully determined slug like `/x/` to a page like `/a/`. It would be nice if this would include the redirection of paths, such that when a visitor types `/x/b` it would redirect to `/a/b/`.

**Comment by yakky** [comment]
Using the current widget you can already set a custom string both as **from** and **to**, just write the string in the popup and confirm using **Enter**

**Comment by exploide** [comment]
Thanks for you reply. Probably we are misunderstanding each other. I try to rephrase my issue:

There is a cms page `a` and multiple subpages, one of this e.g. is `b`. Using this cool app, I can create a redirect, e.g. from `/x/` to page `a`. But it would be awesome if this would automatically redirect `/x/b` to `/a/b`, too. Similar to what this apache directive is doing: `RewriteRule ^/x/(.*) /a/$1 [R=301]`

**Comment by yakky** [comment]
Ah, I see.
It looks feasible: in the end it all boils down to selecting the right Redirect object here: https://github.com/nephila/djangocms-redirect/blob/master/djangocms_redirect/middleware.py#L37-L45
Not sure when i will be able to tackle this, though.

**Comment by yakky** [comment]
@exploide it took a while, but we finally have this :)

**Comment by exploide** [comment]
@yakky thanks, that looks great :)

I'm no longer the admin of the website where I was in need of this feature but once it gets released, I will notify the responsible people. They might still find this useful.

**Comment by yakky** [comment]
@exploide It was any easy guess that this came up a bit too late for your needs, but thanks for reporting this, and I hope it might be of use for you in future projects
