### ISSUE TITLE
Handling of trailing slashes in redirects

### ISSUE THREAD

**Issue by geislern** [nephila/djangocms-redirect#31]
After updating recently, we found that there seems to be no way to create one redirect that works with and without trailing slash, i.e. we want to create either
`/a --> /b/`
OR
`/a/ --> /b/ `
but not both, yet have `mysite/a` and `mysite/a/` both forward to `mysite/b/`

We are convinced this was possible with a previous version (using `/a/ --> /b/ `?) but cannot currently figure out a configuration to make it work without duplicating every redirect...

Any help?

**Comment by yakky** [comment]
What's your `APPEND_SLASH` setting value?
#21 might have had in impact on this behavior,

**Comment by yakky** [comment]
See #32 for a complete set of tests for redirect behavior with and without `/`

**Comment by geislern** [comment]
Thank you, I also suspected #21 might have something to do with this, but wasn't sure. I will check and get back to this issue.

**Comment by geislern** [comment]
Sorry this took so long. In our instance APPEND_SLASH was not explicitly set at all; I believe this defaults to True.
However, neither setting was truly able to fix my problem.

Assuming 1 is a page created with djangocms, such that it appears as site/1. I have two redirects: /a and /b/.
Here's the behaviour I observe:

If I set APPEND_SLASH to False:
- /a works, /a/ does not
- /b works, and so does /b/
- /admin does not work, but /admin/ does
- /1 works but /1/ does not

If I set APPEND_SLASH to True:
- /a works, but /a/ does not 
- /b does not work, but /b/ does
- /admin works, so does /admin/
- /1 works, so does /1/

What I would like to have:
- /a works, so does /a/ OR /b works, so does /b/
- /admin works, so does /admin/
- /1 works, so does /1/

Any suggestion what I could try/what I'm doing wrong?

**Comment by yakky** [comment]
@geislern thanks for the feedback, I will setup a test to reproduce your case to better understand what's going on

**Comment by geislern** [comment]
After some further experimentation, it seems that this also has something to do with internationalization, so a heads up that we use two languages on our site... The behaviour we so far expected to see, but don't, is that a redirect directs to the language the user previously used for the side, or if that is not set the default, which in our case depends on the user's browser settings.

**Comment by Xiphoseer** [comment]
Some additional info:

The selection boxes in the admin interface show the variant without a slash (e.g. `/foo`) for all pages. That affords the user to use that format for all their needs, which (with the current logic) will never be found for an incoming URL that ends with a slash already. So, you could also argue for using always `/foo` form in the database when `APPEND_SLASH` is true, and trim the final slash before lookup.

**Comment by yakky** [comment]
@geislern #37 should have fixed the issue
I will make a release shortly and it would be great if you could give it a run
Please feel free to reopen this if it's not solved

Thanks to @Xiphoseer for their great work on this :clap:

**Comment by Xiphoseer** [comment]
I should probably mention that @geislern and I are working on the same downstream project and it's quite likely that I'll be the one to test this one more time before deploying it.

That said, thank you @yakky for making this contribution process so easy, and following through with a really pleasant CI experience.

**Comment by yakky** [comment]
@Xiphoseer thanks :blush: 
it's been easy to make the process easy with such good contributions :clap:
