### ISSUE TITLE
Error 500 when I put the MIDDLEWARE

### ISSUE THREAD

**Issue by joeljv91** [nephila/djangocms-redirect#6]
Hi,

I'm testing your extension but when I put the MIDDLEWARE the server responds to me with an error 500.

This is the error log:

[Fri Jul 27 12:06:05.489757 2018] [wsgi:error] [pid 19906:tid 139807052039936] [remote 192.168.80.1:49365]     self.load_middleware()
[Fri Jul 27 12:06:05.489767 2018] [wsgi:error] [pid 19906:tid 139807052039936] [remote 192.168.80.1:49365]   File "/var/www/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
[Fri Jul 27 12:06:05.489786 2018] [wsgi:error] [pid 19906:tid 139807052039936] [remote 192.168.80.1:49365]     mw_instance = middleware(handler)
[Fri Jul 27 12:06:05.489811 2018] [wsgi:error] [pid 19906:tid 139807052039936] [remote 192.168.80.1:49365] TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by yakky** [comment]
@joeljv91 thanks for reporting. This is fixed in #7 
We should release a compatible version soon
